### ISSUE TITLE
Rails 5.1

### ISSUE THREAD

**Issue by ThomasConnolly** [assembler/attachinary#147]
Bundler could not find compatible versions for gem "cloudinary":
  In Gemfile:
    cloudinary (~> 1.8)

    attachinary was resolved to 1.3.0, which depends on
      cloudinary (~> 1.0.69)
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1)

    attachinary was resolved to 0.0.1, which depends on
      rails (~> 3.2)

**Comment by webdev1014** [comment]
I've just got same error on rails 5.1.1

Bundler could not find compatible versions for gem "cloudinary":
  In Gemfile:
    cloudinary (~> 1.7.0)

    attachinary (>= 1.3.1, ~> 1.3) was resolved to 1.3.1, which depends on
      cloudinary (~> 1.1.0)

**Comment by ghost** [comment]
+1

**Comment by ctrlaltdylan** [comment]
This gem needs updated to match cloudinary's most recent version - judging by the activity around it I assume this gem is no longer in development?

**Comment by ThomasConnolly** [comment]
I patched the attachinary gem dependencies so it could be used with 
Rails 5; you could use that. I'm not bright enough to do a pull request 
that would update the gem itself. It's so very easy to use attachinary 
and it would be a shame to lose it.

Tom Connolly

**Comment by ctrlaltdylan** [comment]
Thanks Tom - I assume this is your patch? 

https://github.com/ThomasConnolly/attachinary

I use Rails 4.1

**Comment by ThomasConnolly** [comment]
Yes, that's the one. Can you make it a pull request so it becomes the norm?

**Comment by mklb** [comment]
For all having the same problem: The quick fix is to use @ThomasConnolly ´s version right now. Just include it in your gem file as follows:

`gem 'attachinary', :git => 'git://github.com/ThomasConnolly/attachinary.git'`

**Comment by tbsvttr** [comment]
Has this been officially fixed now by now?

**Comment by firecall** [comment]
Updating a project from Rails 4 to 5, and still an issue for me with Rails 5.1.
